version: "3.8"

services:
  pa11y-webservice:
    build: .
    container_name: pa11y-webservice
    environment:
      - MONGODB_URL=mongodb+srv://doadmin:1T4W6gJAj5X3972R@db-mongodb-nyc1-79017-ce73b41b.mongo.ondigitalocean.com/admin?authSource=admin&replicaSet=db-mongodb-nyc1-79017&tls=true
    ports:
      - "3000:3000"
